server:
  port: 80
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DB_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: default
      ssl:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${OAUTH_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
springdoc:
  pathsToMatch: /api/**
jwt:
  expiration: 604800000
  refresh-expiration: 704800000
  secret: ${JWT_SECRET}
google:
  calendar:
    client-id: ${google-client-id}
    client-secret: ${google-client-secret}
    redirect-uri: ${google-calendar_redirect_uri}
  api:
    key: ${GOOGLE_API_KEY}
zoom:
  account-id: ${ZOOM_ACCOUNT_ID}
  client-id: ${ZOOM_CLIENT_ID}
  client-secret: ${ZOOM_CLIENT_SECRET}
kakao:
  middle-location:
    api-key: ${KAKAO_API_KEY}
logging:
  level:
    org.springframework.cloud.gcp.secretmanager: DEBUG
    root: info
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: info

url:
  backend: ${GCP_IP}
front-server:
  domain-A: ${FRONT_DOMAIN_A}
  domain-B: ${FRONT_DOMAIN_B}
  redirect-url: ${FRONT_CALLBACK}
